name: Manhunt
author: MetalNeedles
main: com.metalneedles.manhunt.Manhunt
api-version: '1.20'
version: '${project.version}'
description: '${project.description}'

commands:
  track:
    description: Checks if Manhunt is currently enabled and Enables or Disables the Manhunt.
    usage: /<command>; /<command> status; /<command> enable; /<command> disable
    aliases:
      - settracker
      - hunt