name: Manhunt
author: MetalNeedles
main: com.metalneedles.manhunt.Manhunt
api-version: '1.20'
version: '${project.version}'
description: '${project.description}'

commands:
  manhunt:
    description: Checks if Manhunt is currently enabled and Enables or Disables the Manhunt.
    usage: /<command>; /<command> status; /<command> enable; /<command> disable
  runner:
    description: Checks who the runner(s) is/are or adds runner(s).
    usage: /<command>; /<command> add; /<command> remove; /<command> list; /command clear
    aliases: runners